This notebook is based off of a subsection of the [SGD mnist](https://github.com/fastai/fastai/blob/master/courses/ml1/lesson4-mnist_sgd.ipynb) lesson from fastai 

# Imports and Paths

In [1]:
import numpy as np
from features.core import *

In [14]:
import torch

# Element wise operations

Element wise operations occur when you perform an operation (typically +,-,\*,/,>,<,==) on two tensors of equal rank and size.

## Numpy

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)

[5 7 9]
[-3 -3 -3]


In [9]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,10,(3,3))
print(a)
print(b)

[[7 8 2]
 [9 9 7]
 [8 1 9]]
[[5 3 6]
 [8 5 6]
 [1 8 3]]


In [10]:
print(a+b)

[[12 11  8]
 [17 14 13]
 [ 9  9 12]]


In [11]:
print(a*b)

[[35 24 12]
 [72 45 42]
 [ 8  8 27]]


In [12]:
print(a>b)

[[ True  True False]
 [ True  True  True]
 [ True False  True]]


## PyTorch

Torch can do the same type of element wise operations

In [22]:
a = torch.LongTensor([1,2,3])
b = torch.LongTensor([4,5,6])
print(a+b)
print(a-b)

tensor([ 5,  7,  9])
tensor([-3, -3, -3])


In [23]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,10,(3,3))
a = torch.LongTensor(a)
b = torch.LongTensor(b)
print(a)
print(b)

tensor([[ 7,  0,  0],
        [ 2,  8,  8],
        [ 5,  4,  1]])
tensor([[ 4,  8,  0],
        [ 3,  0,  9],
        [ 9,  8,  5]])


In [24]:
print(a+b)

tensor([[ 11,   8,   0],
        [  5,   8,  17],
        [ 14,  12,   6]])


In [25]:
print(a*b)

tensor([[ 28,   0,   0],
        [  6,   0,  72],
        [ 45,  32,   5]])


In [26]:
print(a>b)

tensor([[ 1,  0,  0],
        [ 0,  1,  0],
        [ 0,  0,  0]], dtype=torch.uint8)


In [37]:
(a<b).to(torch.float).mean()

tensor(0.6667)

The real speed advantage in PyTorch comes when you are able to write loopless code.  For loops in python are on the order of 10,000 times slower than loopless code doing the same vector operations

# Broadcasting

The term **broadcasting** describes how arrays with different shapes are treated during arithmetic operations.  The term broadcasting was first used by Numpy, although is now used in other libraries such as [Tensorflow](https://www.tensorflow.org/performance/xla/broadcasting) and Matlab; the rules can vary by library.

From the [Numpy Documentation](https://docs.scipy.org/doc/numpy-1.10.0/user/basics.broadcasting.html):

    The term broadcasting describes how numpy treats arrays with 
    different shapes during arithmetic operations. Subject to certain 
    constraints, the smaller array is “broadcast” across the larger 
    array so that they have compatible shapes. Broadcasting provides a 
    means of vectorizing array operations so that looping occurs in C
    instead of Python. It does this without making needless copies of 
    data and usually leads to efficient algorithm implementations.
    
In addition to the efficiency of broadcasting, it allows developers to write less code, which typically leads to fewer errors.

*This section was adapted from [Chapter 4](http://nbviewer.jupyter.org/github/fastai/numerical-linear-algebra/blob/master/nbs/4.%20Compressed%20Sensing%20of%20CT%20Scans%20with%20Robust%20Regression.ipynb#4.-Compressed-Sensing-of-CT-Scans-with-Robust-Regression) of the fast.ai [Computational Linear Algebra](https://github.com/fastai/numerical-linear-algebra) course.*

## Broadcasting a scalar to a rank 1 tensor

A rank 1 tensor is also known as a vector (or a 1-d array) and a rank 0 tensor is also known as a scalar

When performing an operation between a rank 0 and rank 1 tensor the rank 0 tensor is **broadcast** to have the same dimensions as the rank 1 tensor

In [39]:
a = np.array([1,2,3])
a > 0

array([ True,  True,  True], dtype=bool)

In [40]:
a+1

array([2, 3, 4])

In [41]:
m = np.array([[1, 2, 3], [4,5,6], [7,8,9]]); m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
2*m*2

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

## Broadcasting a rank 1 tensor (vector) to a rank 2 tensor (matrix)

### numpy

In [46]:
c = np.array([10,20,30]); c

array([10, 20, 30])

In [47]:
m+c

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [48]:
c+m

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [67]:
c*m

array([[ 10,  40,  90],
       [ 40, 100, 180],
       [ 70, 160, 270]])

In [49]:
c.shape

(3,)

If we wanted to add the elements of c row-wise to m, we have to convert c from a rank 1 tensor to a rank 2 tensor

In [51]:
print(c.shape)
print(c[:,None].shape)
print(c[None,:].shape)
print(c[None,:,None].shape)

(3,)
(3, 1)
(1, 3)
(1, 3, 1)


In [54]:
c[:,None]

array([[10],
       [20],
       [30]])

In [55]:
c[:,None] + m

array([[11, 12, 13],
       [24, 25, 26],
       [37, 38, 39]])

We can use `None` when slicing a numpy array to expand the dimensions, this can also be done explicitly with the numpy function `expand_dims`

In [56]:
np.expand_dims(c,0)

array([[10, 20, 30]])

In [57]:
np.expand_dims(c,1)

array([[10],
       [20],
       [30]])

In [60]:
np.expand_dims(c,1).shape

(3, 1)

### Torch

In [64]:
cT = torch.LongTensor(c)
mT = torch.LongTensor(m)
cT

tensor([ 10,  20,  30])

In [65]:
cT+mT

tensor([[ 11,  22,  33],
        [ 14,  25,  36],
        [ 17,  28,  39]])

In [66]:
cT*mT

tensor([[  10,   40,   90],
        [  40,  100,  180],
        [  70,  160,  270]])

In [70]:
cT[:,None]

tensor([[ 10],
        [ 20],
        [ 30]])

## Rules for Broadcasting

When operating on two arrays, Numpy/PyTorch compares their shapes element-wise. It starts with the **trailing dimensions**, and works its way forward. You can think of trailing dimensions as right aligning the dimensions and then reading the dimensions from right to left.  Let's look at 2 cases:

    aa (3d array): 256 x 256 x   3
    bb (2d array):       256 x   3
    
    aa (3d array): 256 x 256 x   3
    cc (2d array):       256 x 256
    
In the first case the trailing dimensions are compatible (see below for definition), while in the second case they are not.    
    
Two dimensions are **compatible** when

- they are equal, or
- one of them is 1

Which means in addition to the case above, the following arrays can also be broadcast

    aa (3d array): 256 x 256 x 3
    dd (2d array):         1 x 3
    
    ee (3d array):   1 x 256 x 3
    ff (2d array): 256 x   1 x 1
 
Whenever a dimension is missing, a 1 is inserted in its place which is why missing dimensions are considered compatible for broadcasting.  Practically, you may want to use broadcasting, when for example, you want to scale each of the threee RGB channels of an image differently.  You can accomplish this by simply multiplying the rank 3 tensor with shape 256 x 256 x 3 by a rank 1 tensor of shape 3.

The [numpy documentation](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html#general-broadcasting-rules) includes several examples of what dimensions can and can not be broadcast together.

In [97]:
aa = np.random.randint(0,9,(256,256,3))
bb = np.random.randint(0,9,(256,3))
cc = np.random.randint(0,9,(256,256))
dd = np.random.randint(0,9,(1,3))
ee = np.random.randint(0,9,(1,256,3))
ff = np.random.randint(0,9,(256,1,1))

In [92]:
(aa+bb).shape

(256, 256, 3)

In [93]:
(aa+cc).shape

ValueError: operands could not be broadcast together with shapes (256,256,3) (256,256) 

In [95]:
(aa+dd).shape

(256, 256, 3)

In [98]:
(ee+ff).shape

(256, 256, 3)

In [130]:
c[:,None], c[None]

(array([[10],
        [20],
        [30]]), array([[10, 20, 30]]))

In [132]:
c[:,None].shape, c[None].shape

((3, 1), (1, 3))

In [131]:
c[:,None] + c[None]

array([[20, 30, 40],
       [30, 40, 50],
       [40, 50, 60]])

In [129]:
c[None] + c[:,None]

array([[20, 30, 40],
       [30, 40, 50],
       [40, 50, 60]])

# Matrix multiplication

## numpy

In [111]:
m, c

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), array([10, 20, 30]))

In [100]:
m @ c

array([140, 320, 500])

In [101]:
np.matmul(m,c)

array([140, 320, 500])

In [102]:
c @ m

array([300, 360, 420])

In [108]:
c[:,None] @ c[:,None]

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [109]:
c[:,None] @ c[None,:]

array([[100, 200, 300],
       [200, 400, 600],
       [300, 600, 900]])

In [110]:
c[None, :] @ c[:, None]

array([[1400]])

Note that just using the multiplicaion symbol, \*, does element wise multiplication, not matrix multiplication 

In [121]:
m * c

array([[ 10,  40,  90],
       [ 40, 100, 180],
       [ 70, 160, 270]])

In [122]:
c * m

array([[ 10,  40,  90],
       [ 40, 100, 180],
       [ 70, 160, 270]])

But we can get matrix multiplication by following the element wise multiplication with summing over the each row

In [133]:
m @ c

array([140, 320, 500])

In [134]:
(m*c).sum(axis=1)

array([140, 320, 500])

In [135]:
(m*c).sum(axis=0)

array([120, 300, 540])

To perform matrix matrix multiplication we need to repeat this step with each column of our second matrix

In [137]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
m @ m

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [143]:
(m*m[:,0]).sum(axis=1)

array([ 30,  66, 102])

In [144]:
(m*m[:,1]).sum(axis=1)

array([ 36,  81, 126])

In [145]:
(m*m[:,2]).sum(axis=1)

array([ 42,  96, 150])

## Torch

In [112]:
mT, cT

(tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]]), tensor([ 10,  20,  30]))

In [113]:
mT @ cT

tensor([ 140,  320,  500])

In [114]:
torch.matmul(mT,cT) 

tensor([ 140,  320,  500])

In [115]:
cT @ mT

tensor([ 300,  360,  420])

In [118]:
cT[:,None] @ cT[:,None]

RuntimeError: size mismatch, m1: [3 x 1], m2: [3 x 1] at /opt/conda/conda-bld/pytorch-cpu_1524582300956/work/aten/src/TH/generic/THTensorMath.c:2033

In [119]:
cT[:,None] @ cT[None,:]

tensor([[ 100,  200,  300],
        [ 200,  400,  600],
        [ 300,  600,  900]])

In [120]:
cT[None, :] @ cT[:, None]

tensor([[ 1400]])

From a machine learning perspective, matrix multiplication is a way of creating features by saying how much we want to weight each input column.  **Different features are different weighted averages of the input columns**. 

The website [matrixmultiplication.xyz](http://matrixmultiplication.xyz/) provides a nice visualization of matrix multiplcation